[package]
name = "gen_enum_cs"
version = "0.1.0"
edition = "2021"

[lib]
name = "gen_cs_code"
crate-type = ["cdylib"]

[dependencies]
askama = "0.12.1"
calamine = "0.26.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
